sudo: false
addons:
  apt:
    packages:
    - unzip
    - gettext
language: ruby
cache: bundler
rvm:
- 2.2.2
branches:
  only:
  - source_middleman
before_script:
- wget https://alioth.debian.org/frs/download.php/latestfile/195/po4a-0.45.tar.gz -O /tmp/po4a-0.45.tar.gz
- tar -xvf /tmp/po4a-0.45.tar.gz
- export PATH=$PATH:$PWD/po4a-0.45/
- export PERLLIB=$PERLLIB:$PWD/po4a-0.45/lib
script:
  - sed -i 's|%W(showtitle |%W(|g' vendor/bundle/ruby/2.2.0/gems/middleman-core-3.3.12/lib/middleman-core/renderers/asciidoc.rb && make build
